### ISSUE TITLE
Signing out without internet makes the app unusable. Even if internet is back on it shows an error (See screenshot)

### ISSUE THREAD

**Issue by josephx86** [EDsteve/ELOC-Control-Panel#17]

**Comment by josephx86** [comment]
@EDsteve  For this issue, on the affected devices/phones, when they are offline(or airplane mode), are you getting that screen (with the try again button) after going through the normal logout/signout process?

**Comment by EDsteve** [comment]
@josephx86 
Hmm. Yesterday (And also a few weeks before) this happened on both phones. Today i tried it and now i only get that issue sometimes. Maybe the problem is connected with my internet connection? Not so sure now.

This is what is (was) happening:

1. Start the app with internet ON
2. turn internet OFF (airplane mode) and then sign out
3. close the app
4. turn internet back ON and start the app
5. then i got this error message with the green button

Yesterday i had to reinstall the app because the app only showed the error with the green button and there was nothing i could do.
Side note: There seems to be two errors. The text is the same. But one has the green button and the other one doesn't show the green button. Not sure if that has something to do with it :)

But i am out now and will investigate further with a video when i am back home again. So maybe before you spend too much time with that issue. Let me recheck it :)

**Comment by josephx86** [comment]
The green "Try Again" button is only available on the screen for verifying
the email address after signing up. So unless I'm missing something, that
might be an older version of the app. Or maybe there is serious bug showing
the wrong screen.

I will wait for your tests.

**Comment by EDsteve** [comment]
@josephx86 
My tests only involving log in and log out (with and without internet). I never try to verify my email. Hmm. It's strange. It happened before on two phones with the first try. 
And now. From around 20 tries i could reproduce the issue only 2 times so far. Didn't find a pattern yet. The app is the newest one from Play Store. The green button appears sometimes though after logging out without internet.

I started recording [this video](https://photos.app.goo.gl/bZD4Z4WS4faU6BgM8) when the green button appeared after i logged out and i turned wifi back on. And even i turn wifi back on. The button still appears. Pressing the button shows no effect. In this case i could log in again after restarting the app the second time. But sometimes the green button error always comes up and i had to reinstall the app.

I would say we just leave this issue for now until i find out more info about it. But i have added [another small issue](https://github.com/EDsteve/ELOC-Control-Panel/issues/16#issue-2600645854) to the list which happens more regularly actually.
