### ISSUE TITLE
App crashes, when trying to connect to a device which is out of reach (pop up: Too far. Get closer to the ELOC)

### ISSUE THREAD

**Issue by josephx86** [EDsteve/ELOC-Control-Panel#20]

**Comment by josephx86** [comment]
[This commit ](https://github.com/EDsteve/ELOC-Control-Panel/commit/c65911423831a26af7038bd976f763be712744a3)should fix this issue. Please test when you can :)

**Comment by EDsteve** [comment]
@josephx86  Thanks for the update. 
One information i just realized today actually:
I was under the impression that the ESP32 module is using the on board PCB antenna (for wifi and BT). But it turned out that the module we are using needs an external antenna. Or a zero ohm resistor has to be connected to the on board antenna. So basically there was no antenna connected. That's why we often had problem connecting to the ELOC. 2m distance gave us -85dB. 
With a resistor in place. We get -60dB at 5m distance. 

So your new code and the HW change should make it bullet proof :)
I will test your new code tomorrow or the day after and report back to you.

**Comment by EDsteve** [comment]
Works like a charm :)
